### ISSUE TITLE
Convert font to path in logo

### ISSUE THREAD

**Issue by xf-** [FreifunkBremen/logo#2]
Current:
Only System with installed font can show logo currently

Solution:
Convert to Path

**Comment by jplitza** [comment]
That's basically what the `homepage.svg` is for, which has the font rendered as a path. The logo.svg is not made for displaying in browsers, but for printing etc., and I think we can reasonably expect people to install the font then. Maybe we should add this as a hint to a readme?

**Comment by xf-** [comment]
Normally only paths are save for print. You need to own or buy a license for that font and most licenses allow to convert font in logo to path. You don't ship the font. I don't know if your license covers font included and shipped via PDF.

**Comment by SimJoSt** [comment]
Also the font is not so easily obtained, as I already experienced in the past.
But most programs will have no problems using the homepage.svg

**Comment by xf-** [comment]
I thought homepage.svg contains different graphic like illustration or layout. This can be closed. 

Maybe remove some overhead in homepage.svg like font and other unused.
Last thing: Why do you use transform additional to coordinates and radius? transform can be a little bit buggy/different behavior in different browser engines. http://caniuse.com/#feat=svg-html

**Comment by jplitza** [comment]
Well yes, homepage.svg also has minor differences (other font color, different spacing).

And we use transform because that's how Inkscape saved the file. I didn't handwrite this SVG.

**Comment by SimJoSt** [comment]
I'm closing this, as @xf- requested it and I don't think we will be optimizing the svgs in the near future, as any future changes made with Inkscape will probably just readd them.
If somebody wants to supply an optimized version, we will be happy to use it :-)
